#!/bin/bash

# this file is automatically generated by kickass-libexec scripts...

export JJLAB_NAME=''www.jjlab.net'';
export JJLAB_CODE=''jjlab'';

export JJLAB_VERSION='0.3.1299';
export JJLAB_VERSION_MAJOR='0';
export JJLAB_VERSION_MINOR='3';
export JJLAB_VERSION_PATCH='1299';

export JJLAB_SVN_DATE='Date: 2024-08-14 16:59:07 +1000 (Wed, 14 Aug 2024)';
export JJLAB_SVN_REVISION='Revision: 40936855817';
export JJLAB_SVN_AUTHOR='Author: jj5';

export JJLAB_GIT_DATE='2024-08-14 16:59:07 +1000 (Wed, 14 Aug 2024)';
