<?php

// this file is automatically generated by kickass-libexec scripts...

// you can change the name but not the code...
define( 'JJLAB_NAME', 'www.jjlab.net' );
define( 'JJLAB_CODE', 'jjlab' );

//define( 'JJLAB_VERSION', '0.3.1267' );
define( 'JJLAB_VERSION_MAJOR', 0 );
define( 'JJLAB_VERSION_MINOR', 3 );
define( 'JJLAB_VERSION_PATCH', 1267 );

define(
  'JJLAB_SVN_DATE',
  '$Date: 2024-08-13 19:17:33 +1000 (Tue, 13 Aug 2024) $'
);
define( 'JJLAB_SVN_REVISION', '$Revision: 22164907025 $' );
define( 'JJLAB_SVN_AUTHOR', '$Author: jj5 $' );

define( 'JJLAB_GIT_DATE', '2024-08-13 19:17:33 +1000 (Tue, 13 Aug 2024)' );
