<?php

// this file is automatically generated by kickass-libexec scripts...

// you can change the name but not the code...
define( 'JJLAB_NAME', 'www.jjlab.net' );
define( 'JJLAB_CODE', 'jjlab' );

//define( 'JJLAB_VERSION', '0.3.2105' );
define( 'JJLAB_VERSION_MAJOR', 0 );
define( 'JJLAB_VERSION_MINOR', 3 );
define( 'JJLAB_VERSION_PATCH', 2105 );

define(
  'JJLAB_SVN_DATE',
  '$Date: 2026-01-02 10:36:59 +1100 (Fri, 02 Jan 2026) $'
);
define( 'JJLAB_SVN_REVISION', '$Revision: 3308548653906 $' );
define( 'JJLAB_SVN_AUTHOR', '$Author: jj5 $' );

define( 'JJLAB_GIT_DATE', '2026-01-02 10:36:59 +1100 (Fri, 02 Jan 2026)' );
