#!/bin/bash

# this file is automatically generated by kickass-libexec scripts...

export JJLAB_NAME='www.jjlab.net';
export JJLAB_CODE='jjlab';

export JJLAB_VERSION='0.3.1869';
export JJLAB_VERSION_MAJOR='0';
export JJLAB_VERSION_MINOR='3';
export JJLAB_VERSION_PATCH='1869';

export JJLAB_SVN_DATE='Date: 2025-06-20 20:34:17 +1000 (Fri, 20 Jun 2025)';
export JJLAB_SVN_REVISION='Revision: 204778009237';
export JJLAB_SVN_AUTHOR='Author: jj5';

export JJLAB_GIT_DATE='2025-06-20 20:34:17 +1000 (Fri, 20 Jun 2025)';
